package com.praca.manager.service;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import com.praca.manager.entity.Customer;
import com.praca.manager.entity.Details;
import org.springframework.stereotype.Service;

import javax.swing.filechooser.FileSystemView;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.Date;

@Service
public class PdfService {

    private final CustomerService customerService;
    private final DetailsService detailsService;
    private Customer customer;
    private Details details;

    private PdfService(CustomerService customerService, DetailsService detailsService){
        this.customerService = customerService;
        this.detailsService = detailsService;
    }

    private static final Font titleFont = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
    private static final Font normalFont = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.NORMAL);
    private static final Font normalBoldFont = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);

    public void newDocument(int customerId, int detailId) throws DocumentException, FileNotFoundException {

        details = detailsService.getDetails(detailId);
        customer = customerService.getCustomer(customerId);

        details.setDelivered(true);
        detailsService.saveDetails(details);

        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream(getDir()));
        System.out.println(getDir());

        document.open();

        document.add(createTitleParagraph());

        document.add(createCustomerParagraph());

        document.add(createDetailParagraph());

        document.add(createSignatureParagraph());

        document.close();
    }

    private Paragraph createTitleParagraph(){

        Paragraph titleParagraph = new Paragraph();
        titleParagraph.add(new Paragraph("Service Card", titleFont));
        addEmptyLine(titleParagraph, 1);

        titleParagraph.add(new Paragraph("Report generated by: "
                + System.getProperty("user.name") + ", " + new Date(), normalBoldFont));
        addEmptyLine(titleParagraph, 1);

        return titleParagraph;
    }

    private Paragraph createCustomerParagraph(){

        Paragraph customerDataParagraph = new Paragraph("Customer Data", titleFont);
        addEmptyLine(customerDataParagraph, 1);

        customerDataParagraph.add(createCustomerTable());
        addEmptyLine(customerDataParagraph, 1);

        return customerDataParagraph;

    }

    private Paragraph createDetailParagraph(){
        Paragraph detailDataParagraph = new Paragraph("Details Data", titleFont);
        addEmptyLine(detailDataParagraph, 1);

        detailDataParagraph.add(createDetailTable());
        addEmptyLine(detailDataParagraph, 2);

        detailDataParagraph.add(new Paragraph("RECEIVED: \n", normalBoldFont));
        detailDataParagraph.add(new Paragraph(details.getReceived(), normalFont));
        addEmptyLine(detailDataParagraph, 1);

        detailDataParagraph.add(new Paragraph("FINISHED: \n", normalBoldFont));
        detailDataParagraph.add(new Paragraph(details.getReturned(),normalFont));
        addEmptyLine(detailDataParagraph, 2);

        detailDataParagraph.add(new Paragraph("SYMPTOMS: \n", normalBoldFont));
        detailDataParagraph.add(new Paragraph(details.getSymptoms(), normalFont));
        addEmptyLine(detailDataParagraph, 1);

        detailDataParagraph.add(new Paragraph("REPAIR DESCRIPTION: \n", normalBoldFont));
        detailDataParagraph.add(new Paragraph(details.getRepair(), normalFont));
        addEmptyLine(detailDataParagraph, 1);

        detailDataParagraph.add(new Paragraph("COMMENT: \n", normalBoldFont));
        detailDataParagraph.add(new Paragraph(details.getComments(), normalFont));
        addEmptyLine(detailDataParagraph, 5);

        return detailDataParagraph;
    }

    private Paragraph createSignatureParagraph(){

        Paragraph signatureParagraph = new Paragraph();
        Chunk customerSignature = new Chunk("customer signature");
        customerSignature.setUnderline(0.1f, -1f);
        Chunk whiteSpace = new Chunk("                                                                               ");
        Chunk serviceTechnicianSignature = new Chunk("service technician signature");
        serviceTechnicianSignature.setUnderline(0.1f, -1f);
        signatureParagraph.add(customerSignature);
        signatureParagraph.add(whiteSpace);
        signatureParagraph.add(serviceTechnicianSignature);

        return signatureParagraph;

    }

    private PdfPTable createCustomerTable(){

        PdfPTable table = new PdfPTable(4);

        PdfPCell c1 = new PdfPCell(new Phrase("Customer ID", normalBoldFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Owner", normalBoldFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Address", normalBoldFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("phone Number", normalBoldFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        PdfPCell data = new PdfPCell(new Phrase(String.valueOf(customer.getCustomerId())));
        data.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(data);

        data = new PdfPCell(new Phrase(customer.getOwner()));
        data.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(data);

        data = new PdfPCell(new Phrase(customer.getAddress()));
        data.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(data);

        data = new PdfPCell(new Phrase(customer.getPhoneNumber()));
        data.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(data);

        return table;
    }

    private PdfPTable createDetailTable(){

        PdfPTable table = new PdfPTable(5);

        PdfPCell cell = new PdfPCell(new Phrase("Manufacturer", normalBoldFont));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);

        cell = new PdfPCell(new Phrase("Pattern", normalBoldFont));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);

        cell = new PdfPCell(new Phrase("Number", normalBoldFont));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);

        cell = new PdfPCell(new Phrase("Power supply", normalBoldFont));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);

        cell = new PdfPCell(new Phrase("battery", normalBoldFont));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);

        cell = new PdfPCell(new Phrase(details.getManufacturer()));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);

        cell = new PdfPCell(new Phrase(details.getManufacturerPattern()));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);

        cell = new PdfPCell(new Phrase(details.getPatternNumber()));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);

        cell = new PdfPCell(new Phrase(details.getPowerSupply()));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);

        if (details.isBattery()){
            cell = new PdfPCell(new Phrase("yes"));
        }else {
            cell = new PdfPCell(new Phrase("no"));
        }
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);

        return table;
    }

    private void addEmptyLine(Paragraph paragraph, int count){
        for (int i=0; i<count; i++){
            paragraph.add(new Paragraph(" "));
        }
    }

    private String getDir(){
        FileSystemView fileSystemView = FileSystemView.getFileSystemView();
        File[] roots = fileSystemView.getRoots();
        String temp = String.valueOf(fileSystemView.getHomeDirectory()) + "/new.pdf";
        return temp.replace('\\', '/');
    }
}